sudo: false
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
    - mongodb-org-shell
language: python
python:
- '3.5'
- '3.4'
before_install:
- mongo --version
install:
- pip install tox-travis coveralls
script: tox
after_success:
- coveralls
deploy:
  provider: pypi
  user: touilleMan
  on:
    tags: true
    repo: Scille/xin-back
  password:
    secure: Q/MVSK1e9ihaKc4vsHk6rNCa0S+Q2AU6uVCaNZY3iWxLScJPHtH2TDfpI8z0NN//93LBqSW0E9CswZ/B0Jcy55N8TSi70pPrYx63+eWxQbXAyAeVSMrsRWt3dDfDuWn/YB1OaP06trcF3gQiBSXLv4s+RQtbuSwJj0PUSWGZONrFiaPZOjTIcQ+kzHj9zJtno3cEUld3BX6s+dy0s0ktCo/QBlpKzy9vOB25mXjOm1kxxtX5VFZ4HAxlhYeY7gVtUlTNkap8FhK4bAN1IflT/SGJ0tHLJnFKk1pCD6cAkdl4y+mdZ1Bo6lH7f8Jt2BWrZNzy0pduq0RH9B/yuAes2KMvmMEdNeKfommxIBH2JvnIU7sCSXor5sYX+DbhD2WVoXvdPE0PWRgwtfYcJeA9xdJ908N5yEkkkVa6pgBotCzFCKZBFUrm2rQjXs/k/0yJyqWLfODEkhxmRR68ZA7JofVyjm3igUZ5HbwIeuehw9fk7FuJjHSaattGjUHteedci30Ch5rJk4pSbP2DDnQGiLumebuPOQRdR5FOSTac42KwAMZw3io5dCExBx1lg9nz9TTgjOe5IeBOHL9D6YqCVV2jMxPj6VPKfLtEQPtpbWMVBhqAiJxucswjvcJ5GQaxidVa30C/tM+4vXnfHHQqi8ceoeSqpzvzT0g2BoqLK6c=
