sudo: false
language: python
services:
- mongodb
python:
- '3.5'
- '3.4'
install:
- pip install tox-travis coveralls
script: tox
after_success:
  - coveralls
deploy:
  provider: pypi
  user: touilleMan
  on:
    tags: true
    repo: Scille/xin-back
